name: 'push-function'
description: 'Push a code function to the Nema platform.'
author: 'Nema Systems, Inc.'

inputs:
  file:
    description: 'The file that contains the function code.'
    required: true

  project:
    description:
      'Link to project in Nema. E.g., `myorganization/default/myproject`.'
    required: true

  id:
    description: 'ID of function you are updating.'
    required: true

  functionType:
    description: 'Type of function you are updating.'
    required: false
    default: ''

  details:
    description:
      'Details of what you want to update (JSON dictionary as string).'
    required: false
    default: '{}'

runs:
  using: node20
  main: ../dist/index.js
env:
  ACTION_ARTIFACT_TYPE: 'function-push'
